[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["node"]
nodeVersion = "18"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
